services:
  redis:
    # image: redis:7-alpine
    # command: redis-server --save ""
    image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.37.2
    command: dragonfly --pipeline_queue_limit=1000000 --dbfilename= --lock_on_hashtags --num_shards=1
    restart: always
    ports:
      - "6379:6379"
    sysctls:
      net.core.somaxconn: '511'
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: procrastinate
    ports:
      - "5432:5432"
